[package]
name = "arrow_msg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
section = { version = "0.2", path = "../section/" }
arrow = "49"
chrono = "0.4"

[dev-dependencies]
quickcheck = "1"
