[package]
name = "mysql_connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.7", features = ["mysql", "runtime-tokio", "tls-rustls", "chrono", "rust_decimal", "uuid", "time"] }
section = { path = "../../../section/" }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.31"
time = "0.3.31"